baseURL = 'https://georgelioris.github.io/'
locale = 'en-us'
title = 'georgelioris'
theme = 'paper'

[params]
  name = 'George Lioris'
  bio = '''
I write software, sometimes words.
Mostly software.
'''
  avatar = '/avatar.jpg'
  color = 'lotus'
  disableHLJS = true
  monoDarkIcon = true

[markup.highlight]
  noClasses = false
  lineNumbersInTable = false
